In [1]:
import numpy as np

np.random.seed(123)  # Setting a seed = 123 help us generate the exact same numbers
                         # next time when we call 123 for reproducibility purposes.
m1 = np.random.randint(0, 100, size = 10) # Create a array of 10 random integers in the interval [0, 100)
m2 = np.random.randint(10, size=(3, 4)) # Create a 3 x 4 array of in the interval [0, 10)
print("The one-dimensional array looks like this:\n", m1)
print("The two-dimensional array looks like this:\n", m2)

The one-dimensional array looks like this:
 [66 92 98 17 83 57 86 97 96 47]
The two-dimensional array looks like this:
 [[9 0 0 9]
 [3 4 0 0]
 [4 1 7 3]]


In [2]:
np.random.seed(12) #use 12 as the seed
m1 = np.random.randint(0, 100, size = 10)
m2 = np.random.randint(10, size=(3, 4))
print("The one-dimensional array looks like this:\n", m1)
print("The two-dimensional array looks like this:\n", m2)

The one-dimensional array looks like this:
 [75 27  6  2  3 67 76 48 22 49]
The two-dimensional array looks like this:
 [[4 5 9 2]
 [6 0 5 8]
 [2 9 3 4]]


In [3]:
np.random.seed(123) #use 123 as the seed
m1 = np.random.randint(0, 100, size = 10)
m2 = np.random.randint(10, size = (2,3))
print("\n", "The one-dimensional array looks like this:\n", "\n","\n" , m1)
print("\n", "The two-dimensional array looks like this:\n", m2)


 The one-dimensional array looks like this:
 
 
 [66 92 98 17 83 57 86 97 96 47]

 The two-dimensional array looks like this:
 [[9 0 0]
 [9 3 4]]


## With the same seed, different users will always get the same result. Python restored a lot of random arrays and named them with seed number. But you have to create array(s) in the same rule and order. 

In [4]:
m1[2]


98

In [5]:
m1[-1]#count from the end

47

In [6]:
m2[2,2]#[row, colum]

IndexError: index 2 is out of bounds for axis 0 with size 2

In [7]:
m2[-1,-2]

3

In [8]:
m1[1:7:2] #【start:stop:step】
        #the start is always included and the stop is always excluded

array([92, 17, 57])

In [9]:
m1[1:7:3]

array([92, 83])

In [10]:
m1[1:8:2]

array([92, 17, 57, 97])

In [11]:
m1[1:8:3]

array([92, 83, 97])

In [12]:
m1[:5] # print subarray m1[start]-m1[4], the subarray before m1[5] and exclude the last one

array([66, 92, 98, 17, 83])

In [13]:
m1[5:] # print subarray m1[5]-m1[end], the subarray after m1[5] and include the first one

array([57, 86, 97, 96, 47])

In [14]:
m1[:1]

array([66])

In [15]:
m1[:0]

array([], dtype=int64)

In [16]:
m1[::2] # every other elements

array([66, 98, 83, 86, 96])

In [17]:
# Challenge: how would you access every other element starting from the second?
m1[1::2]

array([92, 17, 57, 97, 47])

In [18]:
m1[::-1] # all elements, reversed

array([47, 96, 97, 86, 57, 83, 17, 98, 92, 66])

###  [[9 0 0 9]
### [3 4 0 0]
### [4 1 7 3]]

In [19]:
m2[:2, :3] # first two rows, first three columns

array([[9, 0, 0],
       [9, 3, 4]])

In [20]:
m3 = m2[:, 0] # first column
print (m3)

[9 9]


In [21]:
m3 = m2[0, :]  # first row
# This could be written in a compact format
m2[0]
print (m3)

[9 0 0]


In [22]:
m2[m2 > 3] # you can build masking to an array
           # this accesses all the elements greater than 3

array([9, 9, 4])

In [23]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])
m4 = np.vstack([grid+1, grid+1]) #two grids with same row and same colum
m5 = np.vstack([grid, m4])
print(m5)

[[1 2 3]
 [4 5 6]
 [2 3 4]
 [5 6 7]
 [2 3 4]
 [5 6 7]]


In [24]:
np.vstack([grid, grid+1]) # Stack arrays together vertically.
                          # grid + 1 = every element in grid increments 1

array([[1, 2, 3],
       [4, 5, 6],
       [2, 3, 4],
       [5, 6, 7]])

In [25]:
np.hstack([grid, grid+1])# Stack arrays together horizontally.

array([[1, 2, 3, 2, 3, 4],
       [4, 5, 6, 5, 6, 7]])

In [26]:
import pandas as pd
s1 = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])
s1

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [27]:
s1['b']

0.5

In [28]:
s1[3]

1.0

In [29]:
s1['a':'c']   #subarray includes the end

a    0.25
b    0.50
c    0.75
dtype: float64

In [30]:
s1[0:2]       #subarray excludes the end

a    0.25
b    0.50
dtype: float64

In [31]:
s1[(s1 > 0.3) & (s1 < 0.8)]

b    0.50
c    0.75
dtype: float64

## only one &;    don't use && 

In [32]:
s2 = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])
s2

1    a
3    b
5    c
dtype: object

In [33]:
# explicit index when indexing
s2[1]

'a'

In [34]:
s2[1:3]

3    b
5    c
dtype: object

##  if your Series has an explicit integer index, an indexing operation such as data[1] will use the explicit indices, while a slicing operation like data[1:3] will use the implicit Python-style index.

In [35]:
s2.loc[1:3]  #The iloc attribute always refers the implicit array-style

1    a
3    b
dtype: object

In [36]:
ICEdata = pd.read_csv("ICE1_Data.csv")

ICEdata

DBN Quality_Review_Score Progress_Rpt_10-11 Student_Progress_10-11  \
0    01M292           Developing                  C                      C   
1    01M448           Developing                  C                      B   
2    01M450       Well Developed                  A                      B   
3    01M509           Proficient                  C                      C   
4    01M539           Proficient                  A                      A   
..      ...                  ...                ...                    ...   
417  10X696       Well Developed                  A                      A   
418  13K430           Proficient                  B                      B   
419  10X445       Well Developed                  A                      A   
420  14K449       Well Developed                  B                      B   
421  28Q687           Proficient                  A                      B   

     graduation 2010-11  college enroll 2010-11  
0                 0.563                   0.519  
1                 0.707                   0.363  
2                 0.716                   0.692  
3                 0.564                   0.477  
4                 0.953                   0.870  
..                  ...                     ...  
417               1.000                   0.936  
418               0.977                   0.867  
419               1.000                   0.994  
420               0.914                   0.961  
421               1.000                   0.972  

[422 rows x 6 columns]

In [37]:
#ICEdata['Quality_Review_Score']
ICEdata.iloc[:,1]

0          Developing
1          Developing
2      Well Developed
3          Proficient
4          Proficient
            ...      
417    Well Developed
418        Proficient
419    Well Developed
420    Well Developed
421        Proficient
Name: Quality_Review_Score, Length: 422, dtype: object

In [38]:
ICEdata['collegeRate'] = ICEdata['college enroll 2010-11'] / ICEdata['graduation 2010-11']
ICEdata #compute a new colum

DBN Quality_Review_Score Progress_Rpt_10-11 Student_Progress_10-11  \
0    01M292           Developing                  C                      C   
1    01M448           Developing                  C                      B   
2    01M450       Well Developed                  A                      B   
3    01M509           Proficient                  C                      C   
4    01M539           Proficient                  A                      A   
..      ...                  ...                ...                    ...   
417  10X696       Well Developed                  A                      A   
418  13K430           Proficient                  B                      B   
419  10X445       Well Developed                  A                      A   
420  14K449       Well Developed                  B                      B   
421  28Q687           Proficient                  A                      B   

     graduation 2010-11  college enroll 2010-11  collegeRate  
0                 0.563                   0.519     0.921847  
1                 0.707                   0.363     0.513437  
2                 0.716                   0.692     0.966480  
3                 0.564                   0.477     0.845745  
4                 0.953                   0.870     0.912907  
..                  ...                     ...          ...  
417               1.000                   0.936     0.936000  
418               0.977                   0.867     0.887410  
419               1.000                   0.994     0.994000  
420               0.914                   0.961     1.051422  
421               1.000                   0.972     0.972000  

[422 rows x 7 columns]

In [39]:
ICEdata.iloc[:2]  #review the dataframe as an two-dimensional series

DBN Quality_Review_Score Progress_Rpt_10-11 Student_Progress_10-11  \
0  01M292           Developing                  C                      C   
1  01M448           Developing                  C                      B   

   graduation 2010-11  college enroll 2010-11  collegeRate  
0               0.563                   0.519     0.921847  
1               0.707                   0.363     0.513437

In [40]:
ICEdata.iloc[:3, :2]
#ICEdata.loc[:2,:'Quality_Review_Score']

DBN Quality_Review_Score
0  01M292           Developing
1  01M448           Developing
2  01M450       Well Developed

In [41]:
ICEdata.loc[:20, :'Progress_Rpt_10-11']

DBN Quality_Review_Score Progress_Rpt_10-11
0   01M292           Developing                  C
1   01M448           Developing                  C
2   01M450       Well Developed                  A
3   01M509           Proficient                  C
4   01M539           Proficient                  A
5   01M696       Well Developed                  B
6   02M047           Proficient                  C
7   02M288           Proficient                  A
8   02M294       Well Developed                  B
9   02M296           Proficient                  A
10  02M298       Well Developed                  A
11  02M300           Proficient                  B
12  02M303           Proficient                  B
13  02M305           Proficient                  C
14  02M308       Well Developed                  A
15  02M316           Proficient                  B
16  02M374           Proficient                  C
17  02M376       Well Developed                NaN
18  02M392           Proficient                NaN
19  02M393           Proficient                NaN
20  02M399           Proficient                NaN

In [42]:
ICEdata[ICEdata['graduation 2010-11'] >0.75]

DBN Quality_Review_Score Progress_Rpt_10-11 Student_Progress_10-11  \
4    01M539           Proficient                  A                      A   
5    01M696       Well Developed                  B                      C   
7    02M288           Proficient                  A                      B   
9    02M296           Proficient                  A                      A   
10   02M298       Well Developed                  A                      A   
..      ...                  ...                ...                    ...   
417  10X696       Well Developed                  A                      A   
418  13K430           Proficient                  B                      B   
419  10X445       Well Developed                  A                      A   
420  14K449       Well Developed                  B                      B   
421  28Q687           Proficient                  A                      B   

     graduation 2010-11  college enroll 2010-11  collegeRate  
4                 0.953                   0.870     0.912907  
5                 0.976                   0.957     0.980533  
7                 0.820                   0.627     0.764634  
9                 0.793                   0.560     0.706179  
10                0.915                   0.796     0.869945  
..                  ...                     ...          ...  
417               1.000                   0.936     0.936000  
418               0.977                   0.867     0.887410  
419               1.000                   0.994     0.994000  
420               0.914                   0.961     1.051422  
421               1.000                   0.972     0.972000  

[135 rows x 7 columns]

In [43]:
ICEdata[ICEdata.iloc[:,-1]>0.9]
#ICEdata.iloc[:,-1]

DBN Quality_Review_Score Progress_Rpt_10-11 Student_Progress_10-11  \
0    01M292           Developing                  C                      C   
2    01M450       Well Developed                  A                      B   
4    01M539           Proficient                  A                      A   
5    01M696       Well Developed                  B                      C   
12   02M303           Proficient                  B                      C   
21   02M400       Well Developed                  B                      C   
24   02M411       Well Developed                  A                      A   
28   02M416       Well Developed                  A                      A   
29   02M418       Well Developed                  A                      A   
30   02M419           Proficient                  D                      D   
41   02M489       Well Developed                  B                      C   
55   02M580           Proficient                  C                      D   
70   03M541           Proficient                  B                      B   
78   04M610           Proficient                  A                      B   
102  07X500           Proficient                  B                      C   
103  07X520           Proficient                  C                      D   
143  09X413           Proficient                  C                      C   
149  10X141           Proficient                  A                      B   
152  10X237           Proficient                  B                      B   
183  11X513       Well Developed                  B                      B   
201  12X684           Proficient                  C                      D   
208  13K483       Well Developed                  B                      B   
211  13K595       Well Developed                  A                      A   
241  16K393           Proficient                  C                      D   
247  17K382           Developing                  D                      D   
250  17K528           Developing                  C                      C   
255  17K543       Well Developed                  B                      B   
256  17K546       Well Developed                  A                      A   
303  22K405       Well Developed                  C                      C   
306  22K555           Proficient                  A                      A   
312  24Q267           Proficient                  A                      B   
315  24Q299           Proficient                  A                      A   
327  25Q281       Well Developed                  B                      A   
331  25Q525       Well Developed                  A                      A   
359  28Q680           Proficient                  B                      B   
379  30Q575           Proficient                  B                      B   
380  30Q580           Proficient                  B                      B   
381  31R047           Proficient                  A                      A   
383  31R080           Proficient                  A                      B   
414  31R605           Proficient                  A                      A   
416  05M692       Well Developed                  A                      B   
417  10X696       Well Developed                  A                      A   
419  10X445       Well Developed                  A                      A   
420  14K449       Well Developed                  B                      B   
421  28Q687           Proficient                  A                      B   

     graduation 2010-11  college enroll 2010-11  collegeRate  
0                 0.563                   0.519     0.921847  
2                 0.716                   0.692     0.966480  
4                 0.953                   0.870     0.912907  
5                 0.976                   0.957     0.980533  
12                0.553                   0.500     0.904159  
21                0.832                  

In [44]:
m2

array([[9, 0, 0],
       [9, 3, 4]])

In [45]:
m2 < 2

array([[False,  True,  True],
       [False, False, False]])

In [46]:
m2[m2 < 2]

array([0, 0])

In [47]:
mask = (m2 > 2) & (m2 <5) # Writing the mask this way adds the readability
m2[mask]

array([3, 4])

In [48]:
ICEmask = (ICEdata['graduation 2010-11'] > 0.75) & (ICEdata['Progress_Rpt_10-11'] == 'A') & (ICEdata['Student_Progress_10-11'] == 'B')
ICEdata[ICEmask]

DBN                    Quality_Review_Score Progress_Rpt_10-11  \
7    02M288                              Proficient                  A   
25   02M412                              Proficient                  A   
75   04M435                          Well Developed                  A   
78   04M610                              Proficient                  A   
85   05M670                              Developing                  A   
107  07X548                              Proficient                  A   
108  07X551                              Proficient                  A   
147  09X543                          Well Developed                  A   
149  10X141                              Proficient                  A   
158  10X374                          Well Developed                  A   
161  10X437                              Developing                  A   
175  11X275                              Proficient                  A   
206  13K419                              Proficient                  A   
220  14K478                          Well Developed                  A   
251  17K531                              Proficient                  A   
274  19K404                          Well Developed                  A   
305  22K535                          Well Developed                  A   
308  23K514                              Proficient                  A   
334  26Q430                              Proficient                  A   
336  26Q495                          Well Developed                  A   
356  28Q440                              Proficient                  A   
357  28Q505                              Proficient                  A   
358  28Q620                          Well Developed                  A   
383  31R080                              Proficient                  A   
384  31R440                          Well Developed                  A   
413  03M485  Outstanding (only an option in 2007-8)                  A   
415  02M475                          Well Developed                  A   
416  05M692                          Well Developed                  A   
421  28Q687                              Proficient                  A   

    Student_Progress_10-11  graduation 2010-11  college enroll 2010-11  \
7                        B               0.820                   0.627   
25                       B               0.964                   0.774   
75                       B               0.920                   0.757   
78                       B               0.984                   0.982   
85                       B               0.789                   0.559   
107                      B               0.866                   0.663   
108                      B               0.831                   0.605   
147                      B               0.765                   0.319   
149                      B               0.870                   0.784   
158                      B               0.939                     NaN   
161                      B               0.855                   0.325   
175                      B               0.762                   0.517   
206                      B               0.802                   0.399   
220                      B               0.847                   0.432   
251                      B               0.787                   0.433   
274                      B               0.855                   0.538   
305                      B               0.958                   0.862   
308                      B               0.769                   0.467   
334                      B               0.875                   0.680   
336                      B               0.862                   0.745   
356                      B               0.844                   0.649   
357                      B               0.756                   0.529   
358                      B               0.877                   0.697   
383        

In [49]:
def make_df(cols, ind):
    #Quickly make a DataFrame
    data = {c: [str(c) + str(i) for i in ind]
            for c in cols}
    return pd.DataFrame(data, range(4))

# example DataFrame
make_df('ABE', range(4))

A   B   E
0  A0  B0  E0
1  A1  B1  E1
2  A2  B2  E2
3  A3  B3  E3

In [50]:
# This is very similar to np.concatenate() or np.vstack(). 
# By default, the concatenation takes place row-wise within the DataFrame.

df1 = make_df('AB', [1, 2])
df2 = make_df('AB', [3, 4])
print(df1, "\n\n\n\n\n\n\n\n\n")
print(df2, "\n\n\n")
print(pd.concat([df1, df2]))

ValueError: Shape of passed values is (2, 2), indices imply (4, 2)

In [51]:
df3 = make_df('ABC', [1, 2])
df4 = make_df('ACD', [3, 4])
print(df3, "\n\n\n")
print(df4, "\n\n\n")
print(pd.concat([df3, df4]))

ValueError: Shape of passed values is (2, 3), indices imply (4, 3)

In [52]:
pd.concat([df3, df4], join = 'inner')

NameError: name 'df3' is not defined

In [53]:
df5 = pd.DataFrame({'group': ['Accounting', 'Engineering', 'Engineering'],
                    'employee': ['Bob', 'Jake', 'Lisa']})
df6 = pd.DataFrame({'employee': ['Lisa', 'Bob', 'Jake', 'Sue'],
                    'hire_date': [2004, 2008, 2012, 2014]})
dfm = pd.merge(df6, df5)

print(df5, "\n\n\n")
print(df6, "\n\n\n")
print(dfm)

         group employee
0   Accounting      Bob
1  Engineering     Jake
2  Engineering     Lisa 



  employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014 



  employee  hire_date        group
0     Lisa       2004  Engineering
1      Bob       2008   Accounting
2     Jake       2012  Engineering


In [54]:
df6.merge(df5, on='employee', how = 'outer')

employee  hire_date        group
0     Lisa       2004  Engineering
1      Bob       2008   Accounting
2     Jake       2012  Engineering
3      Sue       2014          NaN

In [55]:
df7 = pd.DataFrame({'group': ['Accounting', 'Engineering', 'HR'],
                    'supervisor': ['Carly', 'Guido', 'Steve']})

dfm = pd.merge(df5, df7)
print(df7, "\n\n\n")

print(dfm)

         group supervisor
0   Accounting      Carly
1  Engineering      Guido
2           HR      Steve 



         group employee supervisor
0   Accounting      Bob      Carly
1  Engineering     Jake      Guido
2  Engineering     Lisa      Guido


In [56]:
pd.merge(df5, df6, on='employee')

group employee  hire_date
0   Accounting      Bob       2008
1  Engineering     Jake       2012
2  Engineering     Lisa       2004

In [57]:
df8 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'salary': [70000, 80000, 120000, 90000]})
pd.merge(df5, df8, left_on = 'employee', right_on = 'name')

group employee  name  salary
0   Accounting      Bob   Bob   70000
1  Engineering     Jake  Jake   80000
2  Engineering     Lisa  Lisa  120000

In [58]:
pd.merge(df5, df8, left_on = 'employee', right_on = 'name').drop('name', axis=1)

group employee  salary
0   Accounting      Bob   70000
1  Engineering     Jake   80000
2  Engineering     Lisa  120000

In [59]:
ICEdata.describe(include = 'all')

DBN Quality_Review_Score Progress_Rpt_10-11 Student_Progress_10-11  \
count      422                  368                310                    310   
unique     422                    6                  5                      5   
top     26Q495           Proficient                  A                      C   
freq         1                  186                109                     93   
mean       NaN                  NaN                NaN                    NaN   
std        NaN                  NaN                NaN                    NaN   
min        NaN                  NaN                NaN                    NaN   
25%        NaN                  NaN                NaN                    NaN   
50%        NaN                  NaN                NaN                    NaN   
75%        NaN                  NaN                NaN                    NaN   
max        NaN                  NaN                NaN                    NaN   

        graduation 2010-11  college enroll 2010-11  collegeRate  
count           310.000000              291.000000   291.000000  
unique                 NaN                     NaN          NaN  
top                    NaN                     NaN          NaN  
freq                   NaN                     NaN          NaN  
mean              0.737977                0.531196     0.707836  
std               0.143356                0.193129     0.168986  
min               0.412000                0.141000     0.262570  
25%               0.625250                0.391000     0.589317  
50%               0.726000                0.489000     0.707569  
75%               0.850750                0.656000     0.838918  
max               1.000000                1.000000     1.101227

In [60]:
ICEdata.mean()

graduation 2010-11        0.737977
college enroll 2010-11    0.531196
collegeRate               0.707836
dtype: float64

In [61]:

ICEdata['graduation 2010-11'].max()

1.0

In [62]:
ICEdata.groupby('Quality_Review_Score')

In [63]:
ICEdata.groupby('Quality_Review_Score').mean()

graduation 2010-11  \
Quality_Review_Score                                                     
Developing                                                    0.633019   
Outstanding (only an option in 2007-8)                        0.864333   
Proficient                                                    0.729554   
Underdeveloped                                                0.549667   
Underdeveloped with Proficient Features (only a...                 NaN   
Well Developed                                                0.823367   

                                                    college enroll 2010-11  \
Quality_Review_Score                                                         
Developing                                                        0.402830   
Outstanding (only an option in 2007-8)                            0.747667   
Proficient                                                        0.521208   
Underdeveloped                                                    0.350167   
Underdeveloped with Proficient Features (only a...                     NaN   
Well Developed                                                    0.625871   

                                                    collegeRate  
Quality_Review_Score                                             
Developing                                             0.641309  
Outstanding (only an option in 2007-8)                 0.864183  
Proficient                                             0.703604  
Underdeveloped                                         0.631451  
Underdeveloped with Proficient Features (only a...          NaN  
Well Developed                                         0.752696

In [64]:
ICEdata.groupby('Quality_Review_Score')['graduation 2010-11'].describe()

count      mean       std  \
Quality_Review_Score                                                            
Developing                                           53.0  0.633019  0.107199   
Outstanding (only an option in 2007-8)                3.0  0.864333  0.102051   
Proficient                                          157.0  0.729554  0.135946   
Underdeveloped                                        6.0  0.549667  0.061805   
Underdeveloped with Proficient Features (only a...    0.0       NaN       NaN   
Well Developed                                       90.0  0.823367  0.121570   

                                                      min      25%    50%  \
Quality_Review_Score                                                        
Developing                                          0.457  0.56300  0.615   
Outstanding (only an option in 2007-8)              0.800  0.80550  0.811   
Proficient                                          0.412  0.63000  0.722   
Underdeveloped                                      0.457  0.51525  0.554   
Underdeveloped with Proficient Features (only a...    NaN      NaN    NaN   
Well Developed                                      0.545  0.72775  0.833   

                                                        75%    max  
Quality_Review_Score                                                
Developing                                          0.69800  0.947  
Outstanding (only an option in 2007-8)              0.89650  0.982  
Proficient                                          0.81100  1.000  
Underdeveloped                                      0.59350  0.624  
Underdeveloped with Proficient Features (only a...      NaN    NaN  
Well Developed                                      0.91875  1.000

In [65]:
ICEdata.groupby(['Quality_Review_Score', 'Progress_Rpt_10-11']).count().unstack()
# Here unstack() is just to make the data more readable.
# See descriptions here: https://www.w3resource.com/pandas/dataframe/dataframe-unstack.php

DBN                         \
Progress_Rpt_10-11                         A     B     C     D    F   
Quality_Review_Score                                                  
Developing                               4.0  11.0  19.0  16.0  3.0   
Outstanding (only an option in 2007-8)   3.0   NaN   NaN   NaN  NaN   
Proficient                              48.0  65.0  39.0   5.0  NaN   
Underdeveloped                           NaN   NaN   3.0   1.0  2.0   
Well Developed                          53.0  26.0  11.0   NaN  NaN   

                                       Student_Progress_10-11              \
Progress_Rpt_10-11                                          A     B     C   
Quality_Review_Score                                                        
Developing                                                4.0  11.0  19.0   
Outstanding (only an option in 2007-8)                    3.0   NaN   NaN   
Proficient                                               48.0  65.0  39.0   
Underdeveloped                                            NaN   NaN   3.0   
Well Developed                                           53.0  26.0  11.0   

                                                   ... college enroll 2010-11  \
Progress_Rpt_10-11                         D    F  ...                      A   
Quality_Review_Score                               ...                          
Developing                              16.0  3.0  ...                    3.0   
Outstanding (only an option in 2007-8)   NaN  NaN  ...                    3.0   
Proficient                               5.0  NaN  ...                   45.0   
Underdeveloped                           1.0  2.0  ...                    NaN   
Well Developed                           NaN  NaN  ...                   48.0   

                                                              collegeRate  \
Progress_Rpt_10-11                         B     C     D    F           A   
Quality_Review_Score                                                        
Developing                              11.0  16.0  15.0  2.0         3.0   
Outstanding (only an option in 2007-8)   NaN   NaN   NaN  NaN         3.0   
Proficient                              63.0  37.0   4.0  NaN        45.0   
Underdeveloped                           NaN   3.0   1.0  2.0         NaN   
Well Developed                          26.0  11.0   NaN  NaN        48.0   

                                                               
Progress_Rpt_10-11                         B     C     D    F  
Quality_Review_Score                                           
Developing                              11.0  16.0  15.0  2.0  
Outstanding (only an option in 2007-8)   NaN   NaN   NaN  NaN  
Proficient                              63.0  37.0   4.0  NaN  
Underdeveloped                           NaN   3.0   1.0  2.0  
Well Developed                          26.0  11.0   NaN  NaN  

[5 rows x 25 columns]

In [67]:
ICEdata.groupby('Quality_Review_Score').aggregate(['median', 'min', 'max','mean'])

graduation 2010-11         \
                                                               median    min   
Quality_Review_Score                                                           
Developing                                                      0.615  0.457   
Outstanding (only an option in 2007-8)                          0.811  0.800   
Proficient                                                      0.722  0.412   
Underdeveloped                                                  0.554  0.457   
Underdeveloped with Proficient Features (only a...                NaN    NaN   
Well Developed                                                  0.833  0.545   

                                                                     \
                                                      max      mean   
Quality_Review_Score                                                  
Developing                                          0.947  0.633019   
Outstanding (only an option in 2007-8)              0.982  0.864333   
Proficient                                          1.000  0.729554   
Underdeveloped                                      0.624  0.549667   
Underdeveloped with Proficient Features (only a...    NaN       NaN   
Well Developed                                      1.000  0.823367   

                                                   college enroll 2010-11  \
                                                                   median   
Quality_Review_Score                                                        
Developing                                                         0.4030   
Outstanding (only an option in 2007-8)                             0.6920   
Proficient                                                         0.4900   
Underdeveloped                                                     0.3715   
Underdeveloped with Proficient Features (only a...                    NaN   
Well Developed                                                     0.5920   

                                                                            \
                                                      min    max      mean   
Quality_Review_Score                                                         
Developing                                          0.165  0.658  0.402830   
Outstanding (only an option in 2007-8)              0.690  0.861  0.747667   
Proficient                                          0.183  0.990  0.521208   
Underdeveloped                                      0.141  0.465  0.350167   
Underdeveloped with Proficient Features (only a...    NaN    NaN       NaN   
Well Developed                                      0.268  1.000  0.625871   

                                                   collegeRate            \
                                                        median       min   
Quality_Review_Score                                                       
Developing                                            0.647416  0.271829   
Outstanding (only an option in 2007-8)                0.862500  0.853268   
Proficient                                            0.699735  0.296503   
Underdeveloped                                        0.712859  0.262570   
Underdeveloped with Proficient Features (only a...         NaN       NaN   
Well Developed                                        0.765269  0.388970   

                                                                        
                                                         max      mean  
Quality_Review_Score                                                    
Developing                                          1.048622  0.641309  
Outstanding (only an option in 2007-8)              0.876782  0.864183  
Proficient                                          1.101227  0.703604  
Underdeveloped                                      0.756567  0.631451  
Underdeveloped with Proficient Features (only a...       NaN       NaN  
Well Developed          

In [68]:
ICEdata.groupby(['Quality_Review_Score', 'Progress_Rpt_10-11'])['graduation 2010-11'].aggregate('mean').unstack()

Progress_Rpt_10-11                             A         B         C  \
Quality_Review_Score                                                   
Developing                              0.716500  0.654545  0.639474   
Outstanding (only an option in 2007-8)  0.864333       NaN       NaN   
Proficient                              0.817083  0.722077  0.660333   
Underdeveloped                               NaN       NaN  0.556333   
Well Developed                          0.862472  0.791000  0.711455   

Progress_Rpt_10-11                             D         F  
Quality_Review_Score                                        
Developing                              0.613812  0.504333  
Outstanding (only an option in 2007-8)       NaN       NaN  
Proficient                              0.526400       NaN  
Underdeveloped                          0.457000  0.586000  
Well Developed                               NaN       NaN

In [69]:
ICEdata.pivot_table('graduation 2010-11', index='Quality_Review_Score', columns='Progress_Rpt_10-11')


Progress_Rpt_10-11                             A         B         C  \
Quality_Review_Score                                                   
Developing                              0.716500  0.654545  0.639474   
Outstanding (only an option in 2007-8)  0.864333       NaN       NaN   
Proficient                              0.817083  0.722077  0.660333   
Underdeveloped                               NaN       NaN  0.556333   
Well Developed                          0.862472  0.791000  0.711455   

Progress_Rpt_10-11                             D         F  
Quality_Review_Score                                        
Developing                              0.613812  0.504333  
Outstanding (only an option in 2007-8)       NaN       NaN  
Proficient                              0.526400       NaN  
Underdeveloped                          0.457000  0.586000  
Well Developed                               NaN       NaN

In [70]:
ICEdata.pivot_table('graduation 2010-11',
                    index='Quality_Review_Score',
                    columns='Progress_Rpt_10-11',
                   aggfunc = 'median')

Progress_Rpt_10-11                          A       B      C      D      F
Quality_Review_Score                                                      
Developing                              0.702  0.6290  0.587  0.615  0.506
Outstanding (only an option in 2007-8)  0.811     NaN    NaN    NaN    NaN
Proficient                              0.806  0.7150  0.662  0.531    NaN
Underdeveloped                            NaN     NaN  0.537  0.457  0.586
Well Developed                          0.879  0.8145  0.676    NaN    NaN